apiVersion: v1
kind: ServiceAccount
metadata:
  name: gke-service-account
  namespace: YOU_NAMESPACE
  annotations:
    iam.gke.io/gcp-service-account: "gke-service-account@YOU_PROJECT_ID.iam.gserviceaccount.com"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-accessor
  namespace: YOU_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-accessor
  template:
    metadata:
      labels:
        app: secret-accessor
    spec:
      initContainers:
        - name: fetch-gcloud-secret
          image: google/cloud-sdk:slim
          command: ["/bin/sh", "-c"]
          args:
            - |
              gcloud secrets versions access latest --secret="my-gcr-key-secret" --project="YOU_PROJECT_ID" > /secrets/config.json
              mkdir -p /root/.docker
              cp /secrets/config.json /root/.docker/config.json
          volumeMounts:
            - name: secret-volume
              mountPath: /secrets
      containers:
        - name: main-container
          image: nginx:latest
          command: ["sleep", "infinity"]
          volumeMounts:
            - mountPath: /root/.docker/config.json
              subPath: config.json  # Monta diretamente o arquivo como config.json
              name: secret-volume
      volumes:
        - name: secret-volume
          emptyDir: {}
