apiVersion: v1
kind: ServiceAccount
metadata:
  name: gke-service-account
  namespace: YOU_NAMESPACE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-accessor
  namespace: YOU_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-accessor
  template:
    metadata:
      labels:
        app: secret-accessor
    spec:
      serviceAccountName: gke-service-account
      initContainers:
        - name: fetch-gcloud-secret
          image: google/cloud-sdk:slim
          command: ["/bin/sh", "-c"]
          args:
            - |
              export GOOGLE_APPLICATION_CREDENTIALS=/secrets/service_account.json
              gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
              gcloud secrets versions access latest --secret="my-gcr-key-secret" --project="YOU_PROJECT_ID" > /secrets/.dockerconfigjson
              mkdir -p /root/.docker
              cp /secrets/.dockerconfigjson /root/.docker/config.json
          volumeMounts:
            - name: secret-volume
              mountPath: /secrets
            - name: gcp-key
              mountPath: /secrets/service_account.json
              subPath: service_account.json
      containers:
        - name: main-container
          image: nginx:latest
          command: ["sleep", "infinity"]
          volumeMounts:
            - name: secret-volume
              mountPath: /root/.docker/config.json
              subPath: .dockerconfigjson 
      volumes:
        - name: secret-volume
          emptyDir: {}
        - name: gcp-key
          secret:
            secretName: gcp-key-secret
